from tkinter import*
windows=Tk()
windows.title("Mile to Km converter")
windows.minsize(width=500,height=300)
input=Entry()
input.grid(column=2,row=0)
miles_label = Label(text="Miles")
miles_label.grid(row=0, column=3)
equal_label=Label(text="is equal to")
equal_label.grid(row=1, column=1)
conv_label = Label(text="0")
conv_label.grid(row=1, column=2)
km_label = Label(text="Km")
km_label.grid(row=1, column=3)
def button_click():
    miles=float(input.get())
    km=round(miles*1.60934,2)
    conv_label.config(text=str(km))
button = Button(text="Click Me", command=button_click)
button.grid(row=3,column=2)
windows.mainloop()